#!/usr/bin/env python3
"""Build data.js from accounts_geocoded.json — embed as window.SOPHI_DATA."""
import json

src = json.load(open('/home/user/workspace/sophi-market-map/src/accounts_geocoded.json'))

# Compact tier labels
def short_tier(t):
    if not t: return None
    if t.startswith('A'): return 'A'
    if t.startswith('B'): return 'B'
    if t.startswith('C'): return 'C'
    if t.startswith('D'): return 'D'
    return None

# Clean & compute derived fields
for mk, market in src['markets'].items():
    # compute tier counts
    tier_counts = {'A': 0, 'B': 0, 'C': 0, 'D': 0}
    for a in market['accounts']:
        t = short_tier(a.get('tier'))
        if t: tier_counts[t] += 1
        # Replace tier with short form (keep full label in tier_full)
        a['tier_full'] = a.get('tier')
        a['tier'] = t
    market['tier_counts'] = tier_counts

out = json.dumps(src, default=str, ensure_ascii=False, separators=(',', ':'))

with open('/home/user/workspace/sophi-market-map/data.js', 'w', encoding='utf-8') as f:
    f.write('/* Auto-generated by build_data_js.py — do not edit */\n')
    f.write('window.SOPHI_DATA = ')
    f.write(out)
    f.write(';\n')

print(f'wrote data.js — {len(out):,} bytes')
# totals
total = sum(m['summary']['n_accounts'] for m in src['markets'].values())
tam = sum(m['summary']['tam'] for m in src['markets'].values())
y5 = sum(m['summary']['y5_som'] for m in src['markets'].values())
print(f'  accounts: {total}')
print(f'  tam: ${tam/1e6:.1f}M')
print(f'  y5_som: ${y5/1e6:.1f}M')
