#!/usr/bin/env python3
"""Build v2 data.js from accounts_v2_geocoded.json.

Schema: window.SOPHI_DATA = {markets: {key: {name, state, center, accounts, summary, pool_counts, pool_tam, tier_counts, rollup, pool_structure_rollup, scope}}, meta: {...}}
"""
import json
from pathlib import Path

SRC = Path("/home/user/workspace/sophi-market-map/src")
OUT = Path("/home/user/workspace/sophi-market-map/data.js")

with open(SRC / "accounts_v2_geocoded.json") as f:
    data = json.load(f)

MARKET_CENTERS = {
    "denver":       [-104.9903, 39.7392],
    "charlotte":    [-80.8431, 35.2271],
    "indianapolis": [-86.1581, 39.7684],
    "phoenix":      [-112.0740, 33.4484],
    "cleveland":    [-81.6944, 41.4993],
    "louisville":   [-85.7585, 38.2527],
}

# Trim heavy fields and provide clean account schema
def trim_account(a):
    """Keep only fields the front-end uses."""
    return {
        "name": a["name"],
        "type": a.get("type") or "Other",
        "pool": a["pool"],
        "in_sam": a["in_sam"],
        "rank": a.get("rank"),
        # Money
        "tam": round(a.get("tam") or 0),
        "sam_contrib": round(a.get("sam_contrib") or 0),
        "y1": round(a.get("y1") or 0),
        "y2": round(a.get("y2") or 0),
        "y3": round(a.get("y3") or 0),
        "y4": round(a.get("y4") or 0),
        "y5": round(a.get("y5") or 0),
        # Scoring
        "was": a.get("was"),
        "was_base": a.get("was_base"),
        "was_boost": a.get("was_boost"),
        "tier": _tier(a.get("was")),
        "tier_full": _tier_full(a.get("was")),
        # Lifecycle
        "sign_yr": a.get("sign_yr"),
        "curve": a.get("curve"),
        # Geo
        "lng": a.get("lng"),
        "lat": a.get("lat"),
        "geocoded": a.get("geocoded", False),
        "address": a.get("address") or "",
        "area": a.get("area") or "",
        # Contact / property
        "phone": a.get("phone") or "",
        "email": a.get("email") or "",
        "url": a.get("url") or "",
        "rooms": a.get("rooms"),
        "seats": a.get("seats"),
        "valet_rate": a.get("valet_rate"),
        "self_park_rate": a.get("self_park_rate"),
        "occupancy": a.get("occupancy"),
        "valet_conv": a.get("valet_conv"),
        "gm": a.get("gm") or "",
        "gm_role": a.get("gm_role") or "",
        "management": a.get("management") or "",
        "garage_operator": a.get("garage_operator") or "",
        "valet_operator": a.get("valet_operator") or "",
        "tam_class": a.get("tam_class") or "",
        "tam_status": a.get("tam_status") or "",
        "tam_notes": a.get("tam_notes") or "",
        "location_notes": a.get("location_notes") or "",
        "pool_raw": a.get("pool_raw") or "",
        # Indy v7
        "v7_layer": a.get("v7_layer"),
    }


def _tier(was):
    if was is None: return None
    if was >= 4.0: return "A"
    if was >= 3.4: return "B"
    if was >= 2.8: return "C"
    return "D"


def _tier_full(was):
    if was is None: return None
    if was >= 4.0: return "A — Hero"
    if was >= 3.4: return "B — Core"
    if was >= 2.8: return "C — Opportunistic"
    return "D — Skip / De-prioritize"


# Build output
output = {"markets": {}, "meta": data.get("meta", {})}

for mkey, m in data["markets"].items():
    output["markets"][mkey] = {
        "name": m["name"],
        "state": m["state"],
        "center": MARKET_CENTERS.get(mkey),
        "accounts": [trim_account(a) for a in m["accounts"]],
        "summary": m.get("summary", {}),
        "pool_counts": m.get("pool_counts", {}),
        "pool_tam": m.get("pool_tam", {}),
        "tier_counts": m.get("tier_counts", {}),
        "rollup": m.get("rollup"),
        "pool_structure_rollup": m.get("pool_structure_rollup"),
    }

# Write data.js
with open(OUT, "w") as f:
    f.write("/* Auto-generated by build_data_js_v2.py — do not edit */\n")
    f.write("window.SOPHI_DATA = ")
    json.dump(output, f, separators=(",", ":"), default=str)
    f.write(";\n")

print(f"Wrote {OUT} ({OUT.stat().st_size:,} bytes)")
print(f"Markets: {list(output['markets'].keys())}")
print(f"Total accounts: {sum(len(m['accounts']) for m in output['markets'].values())}")
